services:
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres-db:/var/lib/postgresql/data
    networks:
      - minha-rede
    environment:
      - POSTGRES_PASSWORD=sma-admin
      - POSTGRES_USER=sma-admin
      - POSTGRES_DB=sma-db
  app:
    container_name: go-app
    build: .
    ports:
      - "9090:9090"
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres-db
    networks:
      - minha-rede
    environment:
      - DATABASE_URL=postgres://sma-admin:sma-admin@postgres-db:5432/sma-db?sslmode=disable

volumes:
  postgres_data:
  api_volume:

networks:
  minha-rede:
